name: 'Monkey&hat'
favicon: null
layout_spectrum: 0.4426523
typography_spectrum: 0.39303
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#BEB3A3'
    - '#2F2820'
    - '#6E655B'
    - '#D06D41'
  brandStrength: 0.8125
  lightness: 0.6929533
  saturation: 0.4274264
  rhythmicContrast: 0.6193574
purpose: []
