collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2724014
color:
  saturation: 0.4274264
  brandStrength: 0.522618
  rhythmicContrast: 0.6193574
  brandColors:
    - '#000000'
    - '#BEB3A3'
    - '#2F2820'
    - '#6E655B'
    - '#D06D41'
  lightness: 0.6929533
layout_spectrum: 0.4426523
name: 'Monkey&hat'
